-- ChemicAI. / LDMF-4/7 3.7V — Cérebro Central
-- Execute este arquivo em Supabase > SQL Editor.
-- NUNCA coloque service_role/secret key no frontend.

create table if not exists public.brain_memories (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  description text not null default '',
  features jsonb not null default '{}'::jsonb,
  vector jsonb not null,
  image_url text,
  image2_url text,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brain_history (
  id bigint generated by default as identity primary key,
  memory_id uuid references public.brain_memories(id) on delete set null,
  action text not null check (action in ('insert','update','delete')),
  actor_email text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.brain_memories enable row level security;
alter table public.brain_history enable row level security;

-- Todos podem consultar o conhecimento publicado para fazer análises.
drop policy if exists "public read brain memories" on public.brain_memories;
create policy "public read brain memories"
on public.brain_memories for select
using (true);

-- Somente a conta administradora pode criar/alterar/excluir.
drop policy if exists "admin insert brain memories" on public.brain_memories;
create policy "admin insert brain memories"
on public.brain_memories for insert to authenticated
with check ((auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

drop policy if exists "admin update brain memories" on public.brain_memories;
create policy "admin update brain memories"
on public.brain_memories for update to authenticated
using ((auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com')
with check ((auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

drop policy if exists "admin delete brain memories" on public.brain_memories;
create policy "admin delete brain memories"
on public.brain_memories for delete to authenticated
using ((auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

-- Histórico: somente administrador pode gravar/consultar.
drop policy if exists "admin read brain history" on public.brain_history;
create policy "admin read brain history"
on public.brain_history for select to authenticated
using ((auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

drop policy if exists "admin insert brain history" on public.brain_history;
create policy "admin insert brain history"
on public.brain_history for insert to authenticated
with check ((auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

-- Bucket público para imagens de amostras. O conteúdo pode ser visto no site,
-- mas somente a conta administradora pode enviar/alterar/excluir arquivos.
insert into storage.buckets (id, name, public)
values ('chemicai-images', 'chemicai-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read ChemicAI images" on storage.objects;
create policy "public read ChemicAI images"
on storage.objects for select
using (bucket_id = 'chemicai-images');

drop policy if exists "admin upload ChemicAI images" on storage.objects;
create policy "admin upload ChemicAI images"
on storage.objects for insert to authenticated
with check (bucket_id = 'chemicai-images' and (auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

drop policy if exists "admin update ChemicAI images" on storage.objects;
create policy "admin update ChemicAI images"
on storage.objects for update to authenticated
using (bucket_id = 'chemicai-images' and (auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com')
with check (bucket_id = 'chemicai-images' and (auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

drop policy if exists "admin delete ChemicAI images" on storage.objects;
create policy "admin delete ChemicAI images"
on storage.objects for delete to authenticated
using (bucket_id = 'chemicai-images' and (auth.jwt() ->> 'email') = 'arthurdemeloaraujo10@gmail.com');

create index if not exists brain_memories_label_idx on public.brain_memories(label);
create index if not exists brain_history_memory_idx on public.brain_history(memory_id);
